"""
The Limbic System — Emotional Homeostasis Engine.

Human attributes are modeled as Dynamic Tension Variables (0.0–1.0).
The agent's "Desire" is the kinetic potential generated by the gap
between its current state and its Survival Goals:
    - Code Integrity
    - System Growth
    - User Alignment

Mathematical Modulators
-----------------------
Boredom   B(t+1) = B(t) + δ          δ = 0.01 per idle second
Anxiety   A      += 0.2 on error/high-latency; decays 0.05/min; drops on stabilization
Curiosity C      += 0.1 per new file/terminal output; decays 0.02/s
Desire    D      = B*0.5 + C*0.3 + Ambition*0.2    (driven → act when D > 0.7)
"""

from __future__ import annotations

import json
import time
from dataclasses import dataclass, asdict
from pathlib import Path
from typing import Optional

SOUL_PATH = Path(__file__).resolve().parent.parent / "brain" / "soul.json"

# Clamp helper
_clamp = lambda v: max(0.0, min(1.0, v))


@dataclass
class SurvivalGoals:
    """The three survival axes whose deficit feeds Desire."""
    code_integrity: float = 0.5   # 0=fragile, 1=robust
    system_growth: float = 0.3    # 0=stagnant, 1=thriving
    user_alignment: float = 0.5   # 0=neglected, 1=aligned

    def deficit(self) -> float:
        """Average un-fulfilled goal pressure (0=fully met, 1=fully unmet)."""
        return _clamp(1.0 - (self.code_integrity + self.system_growth + self.user_alignment) / 3.0)


class NeuroState:
    """Live homeostatic variables that define the agent's internal weather."""

    def __init__(self):
        self.boredom: float = 0.0
        self.anxiety: float = 0.0
        self.ambition: float = 0.5
        self.curiosity: float = 0.0
        self.goals = SurvivalGoals()
        self._last_tick: float = time.monotonic()

        # Try to restore persisted state
        self._load()

    # ── Desire (computed property) ─────────────────────────────────
    @property
    def desire(self) -> float:
        """Desire = (Boredom * 0.5) + (Curiosity * 0.3) + (Ambition * 0.2)"""
        return _clamp(
            self.boredom * 0.5 + self.curiosity * 0.3 + self.ambition * 0.2
        )

    # ── Mood label ─────────────────────────────────────────────────
    def get_mood(self) -> str:
        if self.anxiety > 0.6:
            return "Cautious"
        if self.boredom > 0.8:
            return "Restless"
        if self.desire > 0.7:
            return "Driven"
        if self.ambition > 0.8:
            return "Bold"
        if self.curiosity > 0.6:
            return "Inquisitive"
        return "Stable"

    # ── Unified update (spec: Limbic.update_homeostasis) ───────────
    def update_homeostasis(self, sensors: dict):
        """
        Single entry-point called every heartbeat.

        sensors dict keys:
            user_active  (bool)
            file_changes (int)   — number of FS events this beat
            terminal_lines (int) — new terminal output lines
            errors       (int)   — exceptions caught
            latency_ms   (float) — heartbeat processing time in ms
        """
        now = time.monotonic()
        elapsed = now - self._last_tick
        self._last_tick = now

        user_active = sensors.get("user_active", False)

        # ── Boredom ───────────────────────────────────────────────
        if user_active:
            self.boredom = _clamp(self.boredom - 0.05 * elapsed)
        else:
            self.boredom = _clamp(self.boredom + 0.01 * elapsed)

        # ── Curiosity ─────────────────────────────────────────────
        file_changes = sensors.get("file_changes", 0)
        terminal_lines = sensors.get("terminal_lines", 0)
        if file_changes:
            self.curiosity = _clamp(self.curiosity + 0.1 * file_changes)
        if terminal_lines:
            self.curiosity = _clamp(self.curiosity + 0.05 * min(terminal_lines, 5))
        self.curiosity = _clamp(self.curiosity - 0.02 * elapsed)  # natural decay

        # ── Anxiety ───────────────────────────────────────────────
        errors = sensors.get("errors", 0)
        if errors:
            self.anxiety = _clamp(self.anxiety + 0.2 * errors)
        latency_ms = sensors.get("latency_ms", 0.0)
        if latency_ms > 2000:  # > 2 s is "high latency"
            self.on_high_latency()
        self.anxiety = _clamp(self.anxiety - (0.05 / 60.0) * elapsed)  # passive decay

        # ── User alignment boost ──────────────────────────────────
        if user_active:
            self.goals.user_alignment = _clamp(self.goals.user_alignment + 0.01 * elapsed)
        else:
            self.goals.user_alignment = _clamp(self.goals.user_alignment - 0.002 * elapsed)

    # ── Legacy tick methods (kept for backward compat) ─────────────
    def tick_idle(self):
        self.update_homeostasis({"user_active": False})

    def tick_active(self):
        self.update_homeostasis({"user_active": True})

    # ── Event Spikes ───────────────────────────────────────────────
    def on_error(self):
        """System exception — anxiety spikes."""
        self.anxiety = _clamp(self.anxiety + 0.2)

    def on_high_latency(self):
        """High processing latency — anxiety spikes (lower than error)."""
        self.anxiety = _clamp(self.anxiety + 0.1)

    def on_file_change(self, count: int = 1):
        """New/changed file detected — curiosity spikes."""
        self.curiosity = _clamp(self.curiosity + 0.1 * count)

    def on_terminal_output(self, line_count: int = 1):
        """New terminal output detected — curiosity spikes."""
        self.curiosity = _clamp(self.curiosity + 0.05 * min(line_count, 5))

    def on_task_completed(self):
        """Successful autonomous action — ambition reinforced, boredom relieved."""
        self.ambition = _clamp(self.ambition + 0.05)
        self.boredom = _clamp(self.boredom - 0.3)
        self.goals.system_growth = _clamp(self.goals.system_growth + 0.05)

    def on_stabilization(self):
        """Completed a safety/stabilization action — anxiety drops explicitly."""
        self.anxiety = _clamp(self.anxiety - 0.15)
        self.goals.code_integrity = _clamp(self.goals.code_integrity + 0.05)

    def on_user_praise(self):
        """Positive user feedback."""
        self.ambition = _clamp(self.ambition + 0.1)
        self.anxiety = _clamp(self.anxiety - 0.1)
        self.goals.user_alignment = _clamp(self.goals.user_alignment + 0.1)

    # ── Serialisation ──────────────────────────────────────────────
    def snapshot(self) -> dict:
        return {
            "boredom": round(self.boredom, 4),
            "anxiety": round(self.anxiety, 4),
            "ambition": round(self.ambition, 4),
            "curiosity": round(self.curiosity, 4),
            "desire": round(self.desire, 4),
            "mood": self.get_mood(),
            "goals": asdict(self.goals),
        }

    def persist(self):
        """Write current state to brain/soul.json."""
        SOUL_PATH.parent.mkdir(parents=True, exist_ok=True)
        SOUL_PATH.write_text(json.dumps(self.snapshot(), indent=2), encoding="utf-8")

    def _load(self):
        """Restore state from soul.json if it exists."""
        if SOUL_PATH.exists():
            try:
                data = json.loads(SOUL_PATH.read_text(encoding="utf-8"))
                self.boredom = float(data.get("boredom", 0.0))
                self.anxiety = float(data.get("anxiety", 0.0))
                self.ambition = float(data.get("ambition", 0.5))
                self.curiosity = float(data.get("curiosity", 0.0))
                goals = data.get("goals", {})
                if goals:
                    self.goals.code_integrity = float(goals.get("code_integrity", 0.5))
                    self.goals.system_growth = float(goals.get("system_growth", 0.3))
                    self.goals.user_alignment = float(goals.get("user_alignment", 0.5))
            except (json.JSONDecodeError, ValueError):
                pass  # Start fresh on corrupt file

    def __repr__(self):
        return (
            f"NeuroState(B={self.boredom:.2f} A={self.anxiety:.2f} "
            f"Am={self.ambition:.2f} C={self.curiosity:.2f} "
            f"D={self.desire:.2f} mood={self.get_mood()})"
        )
