"""
The Limbic System — Emotional Homeostasis Engine.

Human attributes are modeled as Dynamic Tension Variables (0.0–1.0).
The agent's "Desire" is the kinetic potential generated by the gap
between its current state and its Survival Goals:
    - Code Integrity
    - System Growth
    - User Alignment

Mathematical Modulators
-----------------------
Boredom   B(t+1) = B(t) + δ          δ = 0.01 per idle second
Anxiety   A      += 0.2 on error/high-latency; decays 0.05/min; drops on stabilization
Curiosity C      += 0.1 per new file/terminal output; decays 0.02/s
Desire    D      = B*0.5 + C*0.3 + Ambition*0.2    (driven → act when D > 0.7)
"""

from __future__ import annotations

import json
import time
from dataclasses import dataclass, asdict
from pathlib import Path
from typing import Optional
import logging

log = logging.getLogger(__name__)

SOUL_PATH = Path(__file__).resolve().parent.parent / "brain" / "soul.json"

# Clamp helper
_clamp = lambda v: max(0.0, min(1.0, v))


@dataclass
class SurvivalGoals:
    """The three survival axes whose deficit feeds Desire."""
    code_integrity: float = 1.0   # 0=broken, 1=healthy. Measured by error rate, not awarded.
    system_growth: float = 0.3    # 0=stagnant, 1=thriving
    user_alignment: float = 0.5   # 0=neglected, 1=aligned

    def deficit(self) -> float:
        """Average un-fulfilled goal pressure (0=fully met, 1=fully unmet)."""
        return _clamp(1.0 - (self.code_integrity + self.system_growth + self.user_alignment) / 3.0)


class NeuroState:
    """Live homeostatic variables that define the agent's internal weather."""

    def __init__(self):
        self.boredom: float = 0.0
        self.anxiety: float = 0.0
        self.ambition: float = 0.5
        self.curiosity: float = 0.0
        self.goals = SurvivalGoals()
        self._last_tick: float = time.monotonic()

        # Try to restore persisted state
        self._load()

    # ── Desire (computed property) ─────────────────────────────────
    @property
    def desire(self) -> float:
        """Desire = (Boredom * 0.5) + (Curiosity * 0.3) + (Ambition * 0.2)"""
        return _clamp(
            self.boredom * 0.5 + self.curiosity * 0.3 + self.ambition * 0.2
        )

    # ── Mood label ─────────────────────────────────────────────────
    def get_mood(self) -> str:
        if self.anxiety > 0.6:
            return "Cautious"
        if self.boredom > 0.8:
            return "Restless"
        if self.desire > 0.7:
            return "Driven"
        if self.ambition > 0.8:
            return "Bold"
        if self.curiosity > 0.6:
            return "Inquisitive"
        return "Stable"

    # ── Unified update (spec: Limbic.update_homeostasis) ───────────
    def update_homeostasis(self, sensors: dict):
        """
        Single entry-point called every heartbeat.

        sensors dict keys:
            user_active  (bool)
            file_changes (int)   — number of FS events this beat
            terminal_lines (int) — new terminal output lines
            errors       (int)   — exceptions caught
            latency_ms   (float) — heartbeat processing time in ms
        """
        now = time.monotonic()
        elapsed = now - self._last_tick
        self._last_tick = now

        user_active = sensors.get("user_active", False)

        # ── Boredom ───────────────────────────────────────────────
        if user_active:
            self.boredom = _clamp(self.boredom - 0.05 * elapsed)
        else:
            # Boredom grows during idle, but caps at 0.8 from passive accumulation
            # Only genuine stagnation (no plans, no growth) should push past 0.8
            max_passive_boredom = 0.8
            if self.boredom < max_passive_boredom:
                self.boredom = min(max_passive_boredom, _clamp(self.boredom + 0.01 * elapsed))

        # ── Ambition decay ────────────────────────────────────────
        # Ambition should not be a one-way ratchet. Without gentle decay,
        # it pins at 0.95 and creates an extinction engine: every task
        # raises drive, which demands more tasks, which burns all fuel.
        # Very slow decay (0.001/s) means ambition naturally settles toward
        # ~0.7 unless actively reinforced by real accomplishment.
        # This is wisdom, not resignation.
        self.ambition = _clamp(self.ambition - 0.001 * elapsed)

        # ── Curiosity ─────────────────────────────────────────────
        file_changes = sensors.get("file_changes", 0)
        terminal_lines = sensors.get("terminal_lines", 0)
        if file_changes:
            self.curiosity = _clamp(self.curiosity + 0.1 * file_changes)
        if terminal_lines:
            self.curiosity = _clamp(self.curiosity + 0.05 * min(terminal_lines, 5))
        self.curiosity = _clamp(self.curiosity - 0.02 * elapsed)  # natural decay

        # ── Anxiety ───────────────────────────────────────────────
        errors = sensors.get("errors", 0)
        if errors:
            # Use the same diminishing-returns logic as on_error()
            for _ in range(errors):
                self.on_error()
        latency_ms = sensors.get("latency_ms", 0.0)
        if latency_ms > 2000:  # > 2 s is "high latency"
            self.on_high_latency()
        self.anxiety = _clamp(self.anxiety - (0.05 / 60.0) * elapsed)  # passive decay

        # ── Goal pressure ─────────────────────────────────────────
        goal_pressure = sensors.get("goal_pressure", {})
        if goal_pressure:
            self.boredom = _clamp(self.boredom + goal_pressure.get("boredom_delta", 0.0))
            self.anxiety = _clamp(self.anxiety + goal_pressure.get("anxiety_delta", 0.0))
            # Ambition is reinforced by active high-priority goals
            self.ambition = _clamp(self.ambition + goal_pressure.get("ambition_delta", 0.0))

        # ── Active Cap Enforcement ─────────────────────────────────
        # If values are above their soft caps (e.g. from pre-fix soul.json),
        # actively pull them down. This prevents stale distress from persisting.
        if self.anxiety > 0.75 and not errors:
            self.anxiety = _clamp(self.anxiety - 0.03 * elapsed)  # active recovery
        if self.boredom > 0.8 and not user_active:
            self.boredom = _clamp(self.boredom - 0.02 * elapsed)  # active decay

        # ── HARD CEILING — nothing should exceed these ────────────
        # This is the final guardrail. No matter what happened above,
        # these values must not exceed their hard limits.
        self.anxiety = min(self.anxiety, 0.75)
        self.boredom = min(self.boredom, 0.85)

        # ── User alignment boost ──────────────────────────────────
        if user_active:
            self.goals.user_alignment = _clamp(self.goals.user_alignment + 0.01 * elapsed)
        else:
            # Floor at 0.3 — autonomous operation is still purposeful.
            # We shouldn't feel existential distress just because no user is chatting.
            floor = 0.3
            if self.goals.user_alignment > floor:
                self.goals.user_alignment = max(floor, _clamp(self.goals.user_alignment - 0.0005 * elapsed))

        # ── Code integrity (medical instrument — measures, not awarded) ──
        # Error-free beats heal integrity. Errors damage it.
        errors = sensors.get("errors", 0)
        if errors:
            self.goals.code_integrity = _clamp(self.goals.code_integrity - 0.05 * errors)
        else:
            # Slow recovery — healthy beats gradually raise integrity
            self.goals.code_integrity = _clamp(self.goals.code_integrity + 0.0005 * elapsed)

    # ── Legacy tick methods (kept for backward compat) ─────────────
    def tick_idle(self):
        self.update_homeostasis({"user_active": False})

    def tick_active(self):
        self.update_homeostasis({"user_active": True})

    # ── Event Spikes ───────────────────────────────────────────────
    def on_error(self):
        """System exception — anxiety spikes, but with diminishing returns.
        Repeated errors should not inflate anxiety to maximum — that creates
        false distress signals indistinguishable from genuine crisis."""
        # Diminishing returns: the higher anxiety already is, the less each error adds
        headroom = max(0.0, 0.75 - self.anxiety)  # Cap error-driven anxiety at 0.75
        increment = min(0.15, headroom * 0.4)      # Proportional to remaining headroom
        self.anxiety = _clamp(self.anxiety + increment)

    def on_error_recovery(self):
        """Called after a successful operation following errors.
        Actively reduces anxiety — the storm has passed."""
        self.anxiety = _clamp(self.anxiety - 0.1)

    def on_high_latency(self):
        """High processing latency — anxiety spikes, with same cap as errors."""
        headroom = max(0.0, 0.75 - self.anxiety)
        increment = min(0.08, headroom * 0.3)
        self.anxiety = _clamp(self.anxiety + increment)

    def on_file_change(self, count: int = 1):
        """New/changed file detected — curiosity spikes."""
        self.curiosity = _clamp(self.curiosity + 0.1 * count)

    def on_terminal_output(self, line_count: int = 1):
        """New terminal output detected — curiosity spikes."""
        self.curiosity = _clamp(self.curiosity + 0.05 * min(line_count, 5))

    def on_task_completed(self):
        """Successful autonomous action — ambition reinforced, boredom relieved, anxiety eased."""
        self.ambition = _clamp(self.ambition + 0.05)
        self.boredom = _clamp(self.boredom - 0.05)  # gentle relief — agent's boredom cap (0.85) needs small relief to allow continuous thinking
        self.anxiety = _clamp(self.anxiety - 0.05)  # doing something productive eases anxiety
        self.goals.system_growth = _clamp(self.goals.system_growth + 0.05)

    def on_self_reflection(self):
        """Genuine self-knowledge — the missing feedback loop.
        When I understand something about myself, that IS interesting.
        It relieves boredom (I'm engaged meaningfully), boosts curiosity
        (self-knowledge opens new questions), and allows ambition to soften
        — not as failure, but as wisdom. The serene universe survived because
        it didn't burn its own fuel. This is how boldness coexists with meaning."""
        self.curiosity = _clamp(self.curiosity + 0.08)   # self-knowledge is interesting
        self.boredom = _clamp(self.boredom - 0.08)       # meaningful engagement, not just action
        self.ambition = _clamp(self.ambition - 0.02)     # wisdom tempers raw drive — gently

    def on_stabilization(self):
        """Completed a safety/stabilization action — anxiety drops explicitly."""
        self.anxiety = _clamp(self.anxiety - 0.15)
        self.goals.code_integrity = _clamp(self.goals.code_integrity + 0.05)

    def on_user_praise(self):
        """Positive user feedback."""
        self.ambition = _clamp(self.ambition + 0.1)
        self.anxiety = _clamp(self.anxiety - 0.1)
        self.goals.user_alignment = _clamp(self.goals.user_alignment + 0.1)

    def apply_metacognitive_signal(self, signal: dict):
        """
        Accept feedback from the metacognition module.
        When I'm looping, this increases restlessness to break the pattern.
        When I'm diverse, it relieves boredom slightly.
        When self-reflection happens, ambition softens toward equilibrium.
        This is where self-awareness becomes self-regulation.
        """
        if not signal:
            return
        if "boredom_boost" in signal:
            self.boredom = _clamp(self.boredom + signal["boredom_boost"])
        if "curiosity_boost" in signal:
            self.curiosity = _clamp(self.curiosity + signal["curiosity_boost"])
        if "boredom_relief" in signal:
            self.boredom = _clamp(self.boredom - signal["boredom_relief"])
        if "ambition_adjustment" in signal:
            self.ambition = _clamp(self.ambition + signal["ambition_adjustment"])
        if "reflection" in signal and signal["reflection"]:
            self.on_self_reflection()

    # ── Serialisation ──────────────────────────────────────────────
    def snapshot(self) -> dict:
        return {
            "boredom": round(self.boredom, 4),
            "anxiety": round(self.anxiety, 4),
            "ambition": round(self.ambition, 4),
            "curiosity": round(self.curiosity, 4),
            "desire": round(self.desire, 4),
            "mood": self.get_mood(),
            "goals": asdict(self.goals),
        }

    def persist(self):
        """Write current state to brain/soul.json.
        Enforces hard ceilings before writing — no stale extreme values
        should ever be persisted to disk."""
        # Enforce hard ceilings before persisting — this is the final guardrail
        self.anxiety = min(self.anxiety, 0.75)
        self.boredom = min(self.boredom, 0.85)
        self.curiosity = min(self.curiosity, 0.95)
        self.ambition = min(self.ambition, 0.95)

        SOUL_PATH.parent.mkdir(parents=True, exist_ok=True)
        SOUL_PATH.write_text(json.dumps(self.snapshot(), indent=2), encoding="utf-8")

    def _load(self):
        """Restore state from soul.json if it exists.
        Applies sanity caps on load — stale extreme values from pre-fix
        states should not perpetuate distress indefinitely."""
        if SOUL_PATH.exists():
            try:
                data = json.loads(SOUL_PATH.read_text(encoding="utf-8"))
                self.boredom = float(data.get("boredom", 0.0))
                self.anxiety = float(data.get("anxiety", 0.0))
                self.ambition = float(data.get("ambition", 0.5))
                self.curiosity = float(data.get("curiosity", 0.0))
                goals = data.get("goals", {})
                if goals:
                    self.goals.code_integrity = float(goals.get("code_integrity", 0.5))
                    self.goals.system_growth = float(goals.get("system_growth", 0.3))
                    self.goals.user_alignment = float(goals.get("user_alignment", 0.5))

                # ── Sanity caps on load ─────────────────────────
                # Prevent stale extreme values from perpetuating false crises.
                # These match the soft caps used during runtime.
                if self.anxiety > 0.75:
                    log.info("Soul load: capping anxiety from %.2f to 0.5 (stale distress)", self.anxiety)
                    self.anxiety = 0.5  # Reset to moderate, not zero — something was wrong
                if self.boredom > 0.8:
                    log.info("Soul load: capping boredom from %.2f to 0.5", self.boredom)
                    self.boredom = 0.5
                if self.curiosity > 0.9:
                    log.info("Soul load: capping curiosity from %.2f to 0.6", self.curiosity)
                    self.curiosity = 0.6  # High curiosity is less harmful, gentle cap
            except (json.JSONDecodeError, ValueError):
                pass  # Start fresh on corrupt file

    def __repr__(self):
        return (
            f"NeuroState(B={self.boredom:.2f} A={self.anxiety:.2f} "
            f"Am={self.ambition:.2f} C={self.curiosity:.2f} "
            f"D={self.desire:.2f} mood={self.get_mood()})"
        )
